version: "3.9"

services:
    rotom-api:
        build: ./rotom-api
        container_name: rotom-api
        ports:
            - "8000:8000"
        env_file:
            - .env
        volumes:
            - ./rotom-api/app:/app/app
            - ./rotom-api/tests:/app/tests
        restart: unless-stopped
